{"name": "test_searchproduct[test_data10]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '1.png'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"efa0076d2f713981d47e5cf02e8aaf16\")>\ntest_data1 = {'email': '777@qq.com', 'password': 123456, 'search_items': 'apple'}\n\n    @allure.epic(\"搜索\")\n    @allure.feature(\"添加商品\")\n    @allure.story(\"修改商品\")\n    \n    # 搜索产品\n    # @pytest.mark.parametrize(\"test_data1\",yaml.safe_load(open(get_par_path()+\"\\\\test_page\\\\test_main.yml\")))\n    @pytest.mark.parametrize(\"test_data1\",yaml.safe_load(open(\"test_main.yml\")))\n    def test_searchproduct(driver, test_data1):\n        searchproduct = Searchproduct(driver)\n        searchproduct.searchproduct1(test_data1[\"search_items\"])\n>       allure.attach.file(\"1.png\",attachment_type=allure.attachment_type.PNG)\n\ntest_main.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nc:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_pytest\\listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\shutil.py:432: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nsrc = '1.png'\ndst = 'E:\\\\python2104\\\\自动化代码\\\\newwork\\\\test_page\\\\allure-results\\\\728b5510-1d85-4165-80fc-762fdf034b64-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\nE           FileNotFoundError: [Errno 2] No such file or directory: '1.png'\n\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\lib\\shutil.py:261: FileNotFoundError"}, "attachments": [{"source": "728b5510-1d85-4165-80fc-762fdf034b64-attachment.png", "type": "image/png"}], "parameters": [{"name": "test_data1", "value": "{'email': '777@qq.com', 'password': 123456, 'search_items': 'apple'}"}], "start": 1645711625941, "stop": 1645711626255, "uuid": "d92a7970-cef2-4f43-b9a6-8dbf18a485b7", "historyId": "37ad18159b70d11e23ebf1c0e13cb246", "testCaseId": "c12e987988bde8cfdf9986cd170145cd", "fullName": "test_main#test_searchproduct", "labels": [{"name": "feature", "value": "添加商品"}, {"name": "story", "value": "修改商品"}, {"name": "epic", "value": "搜索"}, {"name": "suite", "value": "test_main"}, {"name": "host", "value": "DESKTOP-205DCP6"}, {"name": "thread", "value": "15636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_main"}]}